version: '3.9'
services:
  frontend:
  # build: directory to build the service
    build: ./flutter_ui
    # Expose port from local machine to container for web version
    ports:
      - "8080:8080"
    volumes:
      - ./flutter_ui:/app
  backend:
    build: ./bill_calculator
    # Expose backend port
    ports:
      - "5000:5000"
    volumes:
      - ./bill_calculator:/app
    environment:
      - FLASK_ENV=development
